version: '3.9'

services:
  tresksites-nuxt:
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      - 'traefik.http.routers.tresksites-nuxt.rule=Host(`${NUXT_PUBLIC_BASE_URL}`)'
      - traefik.docker.network=web
      - traefik.http.routers.tresksites-nuxt.entrypoints=websecure
      - traefik.http.routers.tresksites-nuxt.tls.certresolver=myresolver
    container_name: tresksites-nuxt
    restart: always
    networks:
      - web

networks:
  web:
    external: true
